trigger:
  branches:
    include:
    - master
  paths:
    include:
    - windows-setup/build-*.sh
pr: none

pool:
  vmImage: 'windows-2019'
        
steps:
- script: |
    git clone https://github.com/msys2/msys2-ci-base.git C:\msys64
    rm -rf C:\msys64\.git
  displayName: 'Install MSYS2'
- script: |
    set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
    pacman --noconfirm -Syuu
    pacman --noconfirm -Syuu
    pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-ninja patch
    pacman --noconfirm -S mingw-w64-x86_64-poppler mingw-w64-x86_64-gtk3 mingw-w64-x86_64-libsndfile mingw-w64-x86_64-libzip
    pacman --noconfirm -S mingw-w64-x86_64-portaudio mingw-w64-x86_64-lua mingw-w64-x86_64-gtksourceview4
    pacman --noconfirm -Scc
  env:
    MSYS2_ARCH: x86_64
    MSYSTEM: MINGW64
    CHERE_INVOKING: yes
  displayName: 'Install dependencies on Windows'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'C:\msys64'
    includeRootFolder: true
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/msys.7z'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/msys.7z'
    artifact: 'msys'
