#!/usr/bin/php
<?php

$header = "const char * TOOLBAR_INI = ";
$currentVersion = "";
foreach(file('toolbar.ini') as $l) {
	$l = trim($l);
	$l = str_replace('"', '\\"', $l);
	$header .= "\t\"$l\\n\"\n";
	
	if(substr($l, 0, 10) == "version = ") {
		$currentVersion = trim(substr($l, 10));
	}
}

$header .= ";\n";

$header = "const char * TOOLBAR_VERSION = \"$currentVersion\";\n" . $header;
$header = "// Auto generated file from toolbar.ini (generated by genToolbarIniH.php)\n\n" . $header;


file_put_contents('src/toolbar.ini.h', $header);

?>
