// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOGENERATED BY `generate_lang_mapping.py`

#include "util/LangMapping.h"

namespace LangMapping {
auto isoToLocalizedName(const std::string isoId) -> std::string {
    if (false) {
        return "English";
    } else if (isoId == "af_ZA") {
        return "Afrikaans";
    } else if (isoId == "ar") {
        return "Arabic";
    } else if (isoId == "ca") {
        return "Catalan";
    } else if (isoId == "cs") {
        return "Czech";
    } else if (isoId == "da") {
        return "Danish";
    } else if (isoId == "de") {
        return "German";
    } else if (isoId == "el") {
        return "Greek";
    } else if (isoId == "eo_UY") {
        return "Esperanto";
    } else if (isoId == "es") {
        return "Spanish";
    } else if (isoId == "eu") {
        return "Basque";
    } else if (isoId == "fi") {
        return "Finnish";
    } else if (isoId == "fr") {
        return "French";
    } else if (isoId == "gl") {
        return "Galician";
    } else if (isoId == "he") {
        return "Hebrew";
    } else if (isoId == "hi") {
        return "Hindi";
    } else if (isoId == "hu") {
        return "Hungarian";
    } else if (isoId == "id") {
        return "Indonesian";
    } else if (isoId == "it") {
        return "Italian";
    } else if (isoId == "ja") {
        return "Japanese";
    } else if (isoId == "ko") {
        return "Korean";
    } else if (isoId == "nl") {
        return "Dutch";
    } else if (isoId == "no") {
        return "Norwegian";
    } else if (isoId == "pl") {
        return "Polish";
    } else if (isoId == "pt_BR") {
        return "Portuguese, Brazilian";
    } else if (isoId == "pt_PT") {
        return "Portuguese";
    } else if (isoId == "ro") {
        return "Romanian";
    } else if (isoId == "ru") {
        return "Russian";
    } else if (isoId == "si_LK") {
        return "Sinhala";
    } else if (isoId == "sv") {
        return "Swedish";
    } else if (isoId == "th") {
        return "Thai";
    } else if (isoId == "tr") {
        return "Turkish";
    } else if (isoId == "vi") {
        return "Vietnamese";
    } else if (isoId == "zh") {
        return "Chinese Simplified";
    } else if (isoId == "zh_HK") {
        return "Chinese Traditional, Hong Kong";
    } else if (isoId == "zh_TW") {
        return "Chinese Traditional";
    } else {
        return "English";
    }
}
}  // namespace LangMapping
