# Template for setting up an MSYS2 environment and building Xournal++ on Windows

name: Build xournal++
inputs:
  build_type:
    required: true
    type: string
  cmake_flags:
    default: ''
    type: string
    required: false

runs:
  using: composite
  # Copy of msys2-blob as a temporary fix for Windows CI
  steps:
    - name: 'Install dependencies on Windows'
      run: |
        set PATH="C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem"
        pacman --noconfirm -S mingw-w64-x86_64-imagemagick mingw-w64-x86_64-ninja mingw-w64-x86_64-poppler
        pacman --noconfirm -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-libsndfile mingw-w64-x86_64-libzip
        pacman --noconfirm -S mingw-w64-x86_64-lua mingw-w64-x86_64-portaudio mingw-w64-x86_64-gtksourceview4
      env:
        MSYS2_ARCH: x86_64
        MSYSTEM: MINGW64
        CHERE_INVOKING: yes
      shell: pwsh
  # End msys setup
    - name: 'Create build directory'
      run: |
        set PATH="C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%"
        C:\msys64\usr\bin\bash -lc "mkdir build"
      env:
        MSYS2_ARCH: x86_64
        MSYSTEM: MINGW64
        CHERE_INVOKING: yes
      shell: pwsh
    - name: 'Build Xournal++'
      run: |
        set PATH="C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%"
        C:\msys64\usr\bin\bash -lc "cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ inputs.build_type}} ${{ inputs.cmake_flags }}"
        rem Make sure pot is up to date with sources (maybe translation pipeline is currently running)
        C:\msys64\usr\bin\bash -lc "cmake --build . --target pot"
        C:\msys64\usr\bin\bash -lc "cmake --build . --target translations"
        rem Build Xournal++
        C:\msys64\usr\bin\bash -lc "cmake --build ."
      working-directory: ./build
      env:
        MSYS2_ARCH: x86_64
        MSYSTEM: MINGW64
        CHERE_INVOKING: yes
      shell: pwsh
