#!/usr/bin/env python3
from pathlib import Path

def get_language(file: Path):
    with file.open() as fd:
        for line in fd:
            if "Language" in line:
                return line[line.index(' ')+1:-4]

def main():
    generated_cpp = f'''// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOGENERATED BY `{Path(__file__).name}`

#include "util/LangMapping.h"

namespace LangMapping {{
auto isoToLocalizedName(const std::string isoId) -> std::string {{
    if (false) {{
        return "English";
    }}'''

    po_dir: Path = Path(__file__).parent.parent / 'po'
    for file in po_dir.glob('*.po'):
        lang = get_language(file)
        generated_cpp += f''' else if (isoId == "{file.stem}") {{
        return "{lang}";
    }}'''

    generated_cpp += ''' else {
        return "English";
    }
}
}  // namespace LangMapping\n'''

    Path('./src/util/LangMapping.cpp').write_text(generated_cpp)


if __name__ == '__main__':
    main()

