# Template for running Ubuntu release jobs

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: true
      displayed_name:
        type: string
        required: true
      build_appimage:
        type: boolean
        default: false
      gcc_version:
        default: ''     # This means the package 'gcc'
        type: string
      extra_packages:   # List of extra packages to be installed
        type: string
        default: ''
      container_image:  # if provided, runs in a container (docker...)
        required: false
        type: string
        default: ''
      head_sha:         # SHA of the commit to build. Defaults to the head of the triggering event (cf github doc.)
        type: string
        default: ''
      build_type:
        type: string
        default: 'debugoptimized'
      extra_meson_flags:
        type: string
        default: ''
      artifact_version_suffix:  # Additional version string appended to 1.2.3+dev (for instance) in artifacts names
        type: string
        default: ''
    outputs:
      link:
        description: URL of the produced installer
        value: ${{ jobs.release-linux.outputs.link }}
      link_appimage:
        description: URL of the AppImage (if any)
        value: ${{ jobs.release-linux.outputs.link_appimage }}

jobs:
  release-linux:
    name: Create installer for ${{ inputs.displayed_name }}
    runs-on: ${{ inputs.runner }}
    outputs:
      link: ${{ steps.publish-packages.outputs.artifact-url }}
      link_appimage: ${{ steps.publish-appimage.outputs.artifact-url }}
    container:
      image: ${{ inputs.container_image }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.head_sha }}
      - name: 'Install dependencies (for AppImage)'
        if: ${{ inputs.build_appimage }}
        # Building the appimage requires extra packages (to add them to the appimage)
        uses: ./.github/actions/install_deps_ubuntu
        with:
          gcc_version: ${{inputs.gcc_version}}
          extra_packages: >-
            ${{ inputs.extra_packages }}
            fcitx-frontend-gtk3
            fcitx5-frontend-gtk3
            gcin-gtk3-immodule
            ibus-gtk3
            uim-data
            uim-gtk3-immodule
      - name: 'Install dependencies (no AppImage)'
        if: ${{ ! inputs.build_appimage }}
        uses: ./.github/actions/install_deps_ubuntu
        with:
          gcc_version: ${{inputs.gcc_version}}
          extra_packages: ${{ inputs.extra_packages }}
      - name: 'Build Xournal++'
        id: build-package
        shell: bash
        run: |
          mkdir -p build/packages
          # Append our extra flags to the debian/rules file
          sed -i 's/\(\tdh_auto_configure.*-DENABLE_CPPTRACE=\)false\(.*\)$/\1true \2 ${{ inputs.extra_meson_flags }}/' debian/rules
          DEB_BUILD_OPTIONS="nostrip" dpkg-buildpackage -b
          PACKAGE_FILE=$(find ../xournalpp_*.deb -printf "%f\n" | head -n 1)
          mv "../$PACKAGE_FILE" build/packages/
          echo "package-file=$(pwd)/build/packages/$PACKAGE_FILE" >> $GITHUB_OUTPUT
      - name: 'Create AppImage'
        id: build-appimage
        if: ${{ inputs.build_appimage }}
        shell: bash
        run: |
          # Build AppImage
          export DEB_FILE=${{ steps.build-package.outputs.package-file }}
          export VERSION=$(dpkg-deb -f $DEB_FILE version)
          export ARCH=$(dpkg-deb -f $DEB_FILE architecture)
          export OUTPUT="xournalpp-$VERSION${{ inputs.artifact_version_suffix }}-$ARCH.AppImage"
          ../linux-setup/build_appimage.sh

          mkdir appimage
          mv "$OUTPUT" "$OUTPUT".zsync appimage/
          echo "appimage-arch=$ARCH" >> "$GITHUB_OUTPUT"
        working-directory: ./build
      - name: 'Rename package'
        if: ${{ inputs.artifact_version_suffix != '' }}
        shell: bash
        run: |
          FILE=${{ steps.build-package.outputs.package-file }}
          # If $artifact_version_suffix is `-foobar`, this transforms:
          #      * `xournalpp_2.3.4-` into `xournalpp_2.3.4-foobar-`
          #      * `xournalpp_2.3.4~dev-` into `xournalpp_2.3.4~dev-foobar-`
          #      * `xournalpp_2.3.4+dev-` into `xournalpp_2.3.4+dev-foobar-`
          correct_name="$(echo "$FILE" | sed "s/xournalpp_\(\(\:\?\(\:\?[0-9]\+\.\)\+[0-9]\+\)\(\:\?[+~][^-]\+\)\?\)-/xournalpp_\1${{ inputs.artifact_version_suffix }}-/")"
          echo "moving from $FILE to $correct_name"
          mv "$FILE" "$correct_name" || exit 1
      - name: 'Publish packages'
        id: publish-packages
        uses: actions/upload-artifact@v6
        with:
          name: "Packages ${{ inputs.displayed_name }} ${{ runner.arch }}"
          compression-level: 0
          path: "${{github.workspace}}/build/packages"
          if-no-files-found: error
      - name: 'Publish AppImage'
        id: publish-appimage
        if: ${{ inputs.build_appimage }}
        uses: actions/upload-artifact@v6
        with:
          name: "Linux AppImage ${{ steps.build-appimage.outputs.appimage-arch }} (built on ${{ inputs.displayed_name }})"
          compression-level: 0
          path: "${{github.workspace}}/build/appimage"
          if-no-files-found: error
