trigger: none
pr:
  branches:
    include:
    - '*'
  paths:
    include:
      - '*.c'
      - '*.cpp'
      - '*.h'
      - '*.hpp'
    exclude:
      - po/xournalpp.pot
      - po/*.po

stages:
- stage: 'Build_Test_Stage'
  jobs:
  - job: 'Build_Test'
    pool:
      vmImage: 'ubuntu-20.04'
    displayName: 'Test for correct Clang formatting'
    variables:
    - name: CLANG_FORMAT_VERSIONS
      value: "15 16"
    steps:
    - checkout: self
    - bash: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        for VERSION in $(CLANG_FORMAT_VERSIONS); do
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-$VERSION main"
        done
        sudo apt-get update
        for VERSION in $(CLANG_FORMAT_VERSIONS); do
          sudo apt-get install -y clang-format-$VERSION
        done
      displayName: 'Install clang-format'
    - bash: |
        git config --global clangFormat.extensions "c,h,cpp,hpp,hxx,cxx,cc,hh'"
        #
        echo $(git status)
        git fetch origin $(System.PullRequest.TargetBranch):$(System.PullRequest.TargetBranch)
        git switch -c this_pr 
        git switch $(System.PullRequest.TargetBranch)
        git switch this_pr
        BASE_COMMIT=$(git merge-base this_pr $(System.PullRequest.TargetBranch))
        #
        echo Computing diff to commit hash $BASE_COMMIT
        # Exit on git merge-base failure
        [[ -z "$BASE_COMMIT" ]] && { echo "Error: BASE_COMMIT is empty" ; exit 1; }
        git fetch origin $BASE_COMMIT

        for VERSION in $(CLANG_FORMAT_VERSIONS); do
          echo "Testing $(clang-format-$VERSION --version)"
          # A bug in llvm's .deb packages makes git-clang-format-$VERSION call clang-format instead of clang-format-$VERSION
          # The --binary option gives a workaround
          git clang-format-$VERSION --binary="clang-format-$VERSION" --diff $BASE_COMMIT -- && { echo "Success: changes are compatible with clang-format-$VERSION"; exit 0; }
        done
        # Failure: None of the allowed clang-format versions validated the changes
        echo "Error: changes are not compatible with any of the allowed clang-format versions: $CLANG_FORMAT_VERSIONS"
        exit 1
      displayName: 'Run clang-format on modified files'
