trigger: none
pr:
  branches:
    include:
    - '*'
  paths:
    include:
      - '*.c'
      - '*.cpp'
      - '*.h'
      - '*.hpp'
    exclude:
      - po/xournalpp.pot
      - po/*.po

stages:
- stage: 'Build_Test_Stage'
  jobs:
  - job: 'Build_Test'
    pool:
      vmImage: 'ubuntu-20.04'
    displayName: 'Test for correct Clang formatting'
    steps:
    - checkout: self
    - bash: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main"
        sudo apt-get update
        sudo apt-get install -y clang-format
      displayName: 'Install clang-format'
    - bash: |
        git config --global clangFormat.extensions "c,h,cpp,hpp,hxx,cxx,cc,hh'"
        #
        echo $(git status)
        git fetch origin $(System.PullRequest.TargetBranch):$(System.PullRequest.TargetBranch)
        git switch -c this_pr 
        git switch $(System.PullRequest.TargetBranch)
        git switch this_pr
        BASE_COMMIT=$(git merge-base this_pr $(System.PullRequest.TargetBranch))
        #
        echo Computing diff to commit hash $BASE_COMMIT
        # Exit on git merge-base failure
        [[ -z "$BASE_COMMIT" ]] && { echo "Error: BASE_COMMIT is empty" ; exit 1; }
        git fetch origin $BASE_COMMIT
        
        git clang-format --diff $BASE_COMMIT --
      displayName: 'Run clang-format on modified files'
