trigger: none
pr:
  branches:
    include:
    - '*'
  paths:
    include:
      - 'src/core/plugin/luapi_application.h'

stages:
- stage: 'Build_Test_Stage'
  jobs:
  - job: 'Build_Test'
    pool:
      vmImage: 'ubuntu-20.04'
    displayName: 'Test if lua definitions file is up-to-date'
    steps:
    - checkout: self
    - bash: |
        sudo apt-get update
        sudo apt-get install python3
      displayName: 'Install python3'
    - bash: |
        echo $(git status)
        echo "generate the file fresh"
        if ! python3 scripts/lua_def_file.py ; then
            # Failure: Generating script failed
            echo "Error generating the definitions file"
            exit 1
        fi

        # check if it matches the one present in the repository
        if ! git diff --exit-code plugins/luapi_application.def.lua ; then
            # Failure: lua definitions file is not up-to-date
            echo "Error: generated lua definitions file does not match the present one"
            exit 1
        fi
        echo "Success: lua definitions file is up-to-date"
        exit 0
      displayName: 'Generate lua definitions file and check if the one in the repo is still up-to-date'
